-- MySQL Script generated by MySQL Workbench
-- Mon Sep  1 16:21:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Influencers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Influencers` (
  `idInfluencers` INT NOT NULL AUTO_INCREMENT,
  `nombre_in` VARCHAR(50) NULL,
  `Apellido_pat` VARCHAR(50) NULL,
  `Apellido_mat` VARCHAR(50) NULL,
  `Categoria` VARCHAR(150) NULL,
  `Seguidores` INT NULL,
  `prom_views` FLOAT NULL,
  PRIMARY KEY (`idInfluencers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresas` (
  `idEmpresas` INT NOT NULL AUTO_INCREMENT,
  `rut_empresa` VARCHAR(45) NOT NULL,
  `nombre_empresa` VARCHAR(250) NULL,
  `categoria_empresa` VARCHAR(100) NULL,
  PRIMARY KEY (`idEmpresas`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(250) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(40) NOT NULL,
  `verificado` TINYINT NOT NULL,
  `Influencers_idInfluencers` INT NOT NULL,
  `Empresas_idEmpresas` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuarios` ASC) VISIBLE,
  INDEX `fk_Usuarios_Influencers_idx` (`Influencers_idInfluencers` ASC) VISIBLE,
  INDEX `fk_Usuarios_Empresas1_idx` (`Empresas_idEmpresas` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Influencers`
    FOREIGN KEY (`Influencers_idInfluencers`)
    REFERENCES `mydb`.`Influencers` (`idInfluencers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresas`)
    REFERENCES `mydb`.`Empresas` (`idEmpresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Redes Sociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Redes Sociales` (
  `idRedesSociales` INT NOT NULL AUTO_INCREMENT,
  `Influencers_idInfluencers` INT NOT NULL,
  `Redes Socialescol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRedesSociales`),
  INDEX `fk_Redes Sociales_Influencers1_idx` (`Influencers_idInfluencers` ASC) VISIBLE,
  CONSTRAINT `fk_Redes Sociales_Influencers1`
    FOREIGN KEY (`Influencers_idInfluencers`)
    REFERENCES `mydb`.`Influencers` (`idInfluencers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campañas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campañas` (
  `idCampañas` INT NOT NULL AUTO_INCREMENT,
  `Empresas_idEmpresas` INT NOT NULL,
  PRIMARY KEY (`idCampañas`),
  INDEX `fk_Campañas_Empresas1_idx` (`Empresas_idEmpresas` ASC) VISIBLE,
  CONSTRAINT `fk_Campañas_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresas`)
    REFERENCES `mydb`.`Empresas` (`idEmpresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colaboraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colaboraciones` (
  `idColaboraciones` INT NOT NULL AUTO_INCREMENT,
  `Influencers_idInfluencers` INT NOT NULL,
  `Campañas_idCampañas` INT NOT NULL,
  PRIMARY KEY (`idColaboraciones`),
  INDEX `fk_Colaboraciones_Influencers1_idx` (`Influencers_idInfluencers` ASC) VISIBLE,
  INDEX `fk_Colaboraciones_Campañas1_idx` (`Campañas_idCampañas` ASC) VISIBLE,
  CONSTRAINT `fk_Colaboraciones_Influencers1`
    FOREIGN KEY (`Influencers_idInfluencers`)
    REFERENCES `mydb`.`Influencers` (`idInfluencers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaboraciones_Campañas1`
    FOREIGN KEY (`Campañas_idCampañas`)
    REFERENCES `mydb`.`Campañas` (`idCampañas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MetricasH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MetricasH` (
  `idMetricasH` INT NOT NULL AUTO_INCREMENT,
  `Influencers_idInfluencers` INT NOT NULL,
  PRIMARY KEY (`idMetricasH`),
  INDEX `fk_MetricasH_Influencers1_idx` (`Influencers_idInfluencers` ASC) VISIBLE,
  CONSTRAINT `fk_MetricasH_Influencers1`
    FOREIGN KEY (`Influencers_idInfluencers`)
    REFERENCES `mydb`.`Influencers` (`idInfluencers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
